### PR TITLE
Fixed translations

### PR DESCRIPTION
**Pull request by dodieboy**
Fixed translations link(#91)
Fix about page(#124)

### CODE REVIEW

**Comment by rahiblogger** [comment]
Hello sir,
Can you develop it android as a personal project?

**Comment by dodieboy** [comment]
So sorry, i do not understand what you mean?

**Comment by rahiblogger** [comment]
Do u work on xdm?

**Comment by rahiblogger** [comment]
If u r working on XDM so u know everything about this software.

Can you take a personal project?
To make this software in android.

**Comment by dodieboy** [comment]
I only know basic java, never try building a software by myself before. So i dont think i'm skilled enough to the android app yet, may try in the future, but will not be now

**Pull request closed without merging**
