### PR TITLE
Fixed bug, where ~/Downloads folder keeps getting recreated #431

### LINKED ISSUE #431: "Downloads" folder keeps recreating itself
### Short Info
**PC:** Asus K55VD
**OS:** Xubuntu 20.04
**Browser:** Chrome v87.0.4280.88
**XDMan Version:** 7.2.11

### Problem
I really like XDM, after all, there are no another user-friendly download managers for Linux except XDMan as far as i am concerned. But when I change my download folder and delete the "Downloads" folder, XDM recreates that "Downloads" folder. Interestingly, when I download something, files are not getting saved to "Downloads" but folder is showing up anyway.

I can live with that as it is not causing me any major problem but my system language is not English and It's kinda odd to see two Download folders in the home directory. Does anyone know how to fix this or am I the only one?

Ekran görüntüsü_2020-12-17_18-51-30

### PR DESCRIPTION
**Pull request by Borwe**
Fixes #431.
Fix where Downloads folder keeps being recreated, from issue #431

### CODE REVIEW

**Comment by objectProgrammer** [comment]
Hi, please put `Fixes #431` to the top of your comment so that the issue gets closed automatically if/when this gets merged.

**Comment by Borwe** [comment]
> 
> 
> Hi, please put `Fixes #431` to the top of your comment so that the issue gets closed automatically if/when this gets merged.

Like that?

**Comment by objectProgrammer** [comment]
There seems to be a line ending issue here, either the project is LF and your code is CRLF, or the other way around. Could you correct it (In IntelliJ it is at the bottom-right corner)? Of course, this is not a common problem because most projects have a .gitattributes which converts automatically.

**Comment by Borwe** [comment]
> There seems to be a line ending issue here, either the project is LF and your code is CRLF, or the other way around. Could you correct it (In IntelliJ it is at the bottom-right corner)? Of course, this is not a common problem because most projects have a .gitattributes which converts automatically.

So which one should I change to? CRLF or LF ?

**Comment by candrapersada** [comment]
every time you change the download location, but the download location will be set again to default on the next download?

**Comment by Borwe** [comment]
> every time you change the download location, but the download location will be set again to ~/Downloads on the next download?
> Capture3

Hey, this happens with my branch?

**Comment by candrapersada** [comment]
> Can you also mention steps to reproduce

what do you mean by the steps to produce?

**Comment by Borwe** [comment]
> > Can you also mention steps to reproduce
> 
> what do you mean by the steps to produce?

I was fixing bug where if you change default Downloads dir, and delete the file, the ~/Downloads dir will still always keep being created according #431

**Comment by Borwe** [comment]
> There seems to be a line ending issue here, either the project is LF and your code is CRLF, or the other way around. Could you correct it (In IntelliJ it is at the bottom-right corner)? Of course, this is not a common problem because most projects have a .gitattributes which converts automatically.

Yes, the Project is actually CRLF , while my source was LF updated it.

**Comment by Moltkex** [comment]
I changed the default download dir, and it didn't work; downloads dir gets recreated. Using XDM 7.2.11

**Pull request closed without merging**
